.PHONY: clean All

All:
	@echo "----------Building project:[ SELECTION_SORT - Debug ]----------"
	@cd "SELECTION_SORT" && "$(MAKE)" -f  "SELECTION_SORT.mk"
clean:
	@echo "----------Cleaning project:[ SELECTION_SORT - Debug ]----------"
	@cd "SELECTION_SORT" && "$(MAKE)" -f  "SELECTION_SORT.mk" clean
