.PHONY: clean All

All:
	@echo "----------Building project:[ BINARY_SEARCH - Debug ]----------"
	@cd "BINARY_SEARCH" && "$(MAKE)" -f  "BINARY_SEARCH.mk"
clean:
	@echo "----------Cleaning project:[ BINARY_SEARCH - Debug ]----------"
	@cd "BINARY_SEARCH" && "$(MAKE)" -f  "BINARY_SEARCH.mk" clean
